language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
env:
  - PYTHON=""
matrix:
  fast_finish: true
jobs:
  allow_failures:
    - julia: nightly
    - script: bash ./docs/travis.sh
  include:
    - stage: "Nightly"
      julia: nightly
      after_success: skip
    - os: linux
    - os: osx
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script: bash ./docs/travis.sh
      after_success: skip
notifications:
  email: false
codecov: true
coveralls: true
