name = "ElectromagneticFields"
uuid = "d6c1ba6f-ee03-53af-b876-68cefeb88ec8"
authors = ["Michael Kraus <michael.kraus@ipp.mpg.de>"]
version = "0.2.1"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SymPy = "24249f21-da20-56a4-8eb1-6a02cf4ae2e6"

[compat]
Combinatorics = "^1.0"
Documenter = "^0.23, 0.24"
SafeTestsets = "^0.0.1"
SymPy = "^1.0"
julia = "^1.1"

[extras]
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets"]
